FROM ubuntu:latest

RUN useradd -m fluentd

RUN apt-get update && apt-get install -y \
    ruby ruby-dev build-essential \
    && gem install fluentd --no-document

COPY /conf/fluent.conf /etc/fluent/fluent.conf 

USER fluentd

RUN mkdir -p /tmp/logs

CMD ["fluentd", "-c", "/etc/fluent/fluent.conf"]
